### ISSUE TITLE
packer :destroy action searches nodes using attributes from datasift-machine

### ISSUE THREAD

**Issue by borntyping** [rsr5/fragments#2]
https://github.com/rsr5/fragments/blob/master/resources/packer.rb#L200-L201

Should this use `MachinePacker.get.machines` like the other `packer` actions?

**Comment by rsr5** [comment]
No.  It uses search so that it destroys all the VMS you have even if you have changed your fragments/run list and therefore what machines the packer thinks you have.

**Comment by borntyping** [comment]
That makes sense, thanks. (I ran into this becuase something is clearing the node data before the destroy action is run.)
